version: '3'
services:
  arise-backend:
    image: ghcr.io/arise-travel/arise-backend-test-graphql-server:latest
    ports:
      - "4000:4000"
  gmah-adapter:
    image: node:16-alpine
    environment:
      - GRAPHQL_ENDPOINT=http://arise-backend:4000/graphql
      - NODE_ENV=development
      - LISTENING_PORT=8080
    ports:
      - "8080:8080"
    user: ${UID}
    working_dir: /app
    volumes:
      - ./Integrations/GMAH/:/app
    ulimits:
      nofile:
        soft: 98304
        hard: 98304
    command: >
      sh -c "yarn install && npm install -g nodemon && node src/index.js"
